### ISSUE TITLE
draft to final needs

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/habitat-report-card#3]
- [x] combine table on first page for 2023 and totals to date, do same for callout text in blue (currently not in the summaries page)
- [x] link to restoration potential map as mapview (need to create) and text directing reader to URL
- [x] callout rows on progress table on page 2 for habitats not meeting targets goals? 
- [ ] move 2023 barplot to overall project plot to combine legend
- [ ] combine 2023 and progress to date sections on first page
- [x] high res table export
- [x] separate image for progress to date into its own file
- [x] progress table as highres image (should be able to webshot direct from url)

**Comment by fawda123** [comment]
One more idea, likely not suitable for the report card - create a function to show barplot of acres over time for habitat types with 2030 target and 2050 goal, with trend lines used to get color in the report card plot.  Color trend line by color in report card plot. This would be in tbeptools.

**Comment by fawda123** [comment]
restoration map link here: https://tbep-tech.github.io/habitat-report-card/restpotential.html

**Comment by kflahertywalia** [comment]
Comments from HRC member to consider: 

- [ ] Is there anything specific you want to convey with the map of projects (Figure 2)? In my opinion it doesn't really add much unless there is something about the density/distribution you'd like to highlight. I TOTALLY understand why the figure is there but if the report card is too busy and you're looking for ways to simplify it, I think this figure can go. 

- [ ] I like the stoplight chart but if the colors are giving people problems, I think it could be simplified to a traditional red, yellow, green. Red and green stay the same and the yellow/orange and light green could be combined to a yellow. I think both of those categories are expressing similar sentiments - maybe OK/maybe not. If I'm the person preparing this report, I get why the four categories were used. But to most outsiders, I think red, yellow, green would suffice.
