### ISSUE TITLE
move legend

### ISSUE THREAD

**Issue by kflahertywalia** [tbep-tech/habitat-report-card#4]
For the [report card graphic](https://github.com/tbep-tech/habitat-report-card/blob/main/docs/figs/hmpreport.png), it may fit better on the 2 pager if the legend is moved to the bottom.

**Comment by kflahertywalia** [comment]
Also, coastal uplands need to be moved into the "supratidal" box.

**Comment by fawda123** [comment]
@kflahertywalia both should be fixed now.  There's a bit of extra white space on the plot that I can't seem to remove, but you can just crop that out on Google Slides.  I replaced it :)
