### ISSUE TITLE
Remove Intertidal Estuarine (other) category from figures

### ISSUE THREAD

**Issue by kflahertywalia** [tbep-tech/habitat-report-card#6]
Since we got rid of this category for the tables, it should probably be updated on the [bar](https://github.com/tbep-tech/habitat-report-card/blob/main/docs/figs/curbar.png), [pie](https://github.com/tbep-tech/habitat-report-card/blob/main/docs/figs/curpie.png), and [stack](https://github.com/tbep-tech/habitat-report-card/blob/main/docs/figs/curstack.png) figures. BUT partners actually entered that as a habitat in the database in 2024, so not sure exactly how to handle this one... maybe keep it for the projects, but not for the mapping based report card?

**Comment by fawda123** [comment]
Easy to remove, but I think it makes sense to keep it since it describes additional projects.  The 'total intertidal' on the mapping side is just a sum of existing categories, so it was redundant.

**Comment by kflahertywalia** [comment]
Yeah, let's keep it for that part.
